name: Main

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-workflow:
    name: Main workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: "✅"
          BRANCH_NAME: "main"
          IMAGES_FOLDER: "generated"
          GIT_USER_EMAIL: "farihasultana237@gmail.com"
          GIT_USER_NAME: "Fariha Sultana"
          
