name: Update WakaTime Graph

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Clone repository
        run: git clone https://github.com/farihazultana/Farihazultana.git

      - name: Run WakaTime script
        run: |
          cd your-repo
          pip install wakatime
          python wakatime_script.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update WakaTime graph"
          git push
